//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoniz.CostAccounting.FormulationContext.Resources.FormulationAggregate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormulationException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormulationException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shoniz.CostAccounting.FormulationContext.Resources.FormulationAggregate.Formulati" +
                            "onException", typeof(FormulationException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد کالا در یک فرمول نباید تکراری باشد.
        /// </summary>
        public static string AddFormulationDetailDuplicatedGoodsCodeInOneFormulaException {
            get {
                return ResourceManager.GetString("AddFormulationDetailDuplicatedGoodsCodeInOneFormulaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد محصول و تاریخ شروع تکراری می باشد.
        /// </summary>
        public static string AddFormulationDuplicatedProductCodeAndStartDateException {
            get {
                return ResourceManager.GetString("AddFormulationDuplicatedProductCodeAndStartDateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا تائید شده است.
        /// </summary>
        public static string ConfirmingAlreadyConfirmedException {
            get {
                return ResourceManager.GetString("ConfirmingAlreadyConfirmedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمولاسیون بدون امضاء، قابل تائید نیست.
        /// </summary>
        public static string ConfirmingNotRegulatorSignedException {
            get {
                return ResourceManager.GetString("ConfirmingNotRegulatorSignedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف جزئیات فرمولاسیون امضاء شده، امکان پذیر نیست.
        /// </summary>
        public static string DeleteFormulationDetailSignedException {
            get {
                return ResourceManager.GetString("DeleteFormulationDetailSignedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف فرمولاسیون امضاء شده، امکان پذیر نیست.
        /// </summary>
        public static string DeleteFormulationSignedException {
            get {
                return ResourceManager.GetString("DeleteFormulationSignedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف فرمولاسیون دارای جزئیات، امکان پذیر نیست.
        /// </summary>
        public static string DeleteFormulationWithItemsException {
            get {
                return ResourceManager.GetString("DeleteFormulationWithItemsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار دور ریز محاسبه شده نباید کمتر از صفر باشد.
        /// </summary>
        public static string DroppedAmountLessThanZeroException {
            get {
                return ResourceManager.GetString("DroppedAmountLessThanZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد دور ریز محاسبه شده نباید کمتر از صفر باشد.
        /// </summary>
        public static string DroppedPercentLessThanZeroException {
            get {
                return ResourceManager.GetString("DroppedPercentLessThanZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد دور ریز محاسبه شده نباید بیشتر از 100 باشد.
        /// </summary>
        public static string DroppedPercentMoreThan100Exception {
            get {
                return ResourceManager.GetString("DroppedPercentMoreThan100Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد کالا نباید خالی باشد.
        /// </summary>
        public static string GoodsCodeCanNotBeNullException {
            get {
                return ResourceManager.GetString("GoodsCodeCanNotBeNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد رطوبت نباید کمتر از صفر باشد.
        /// </summary>
        public static string HumidityPercentLessThanZeroException {
            get {
                return ResourceManager.GetString("HumidityPercentLessThanZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد رطوبت نباید بیشتر از 100 باشد.
        /// </summary>
        public static string HumidityPercentMoreThan100Exception {
            get {
                return ResourceManager.GetString("HumidityPercentMoreThan100Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار تائید کننده فرمولاسیون، نامعتبر می باشد.
        /// </summary>
        public static string InvalidFormulationConfirmException {
            get {
                return ResourceManager.GetString("InvalidFormulationConfirmException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار ثبات جزئیات فرمولاسیون، نامعتبر می باشد.
        /// </summary>
        public static string InvalidFormulationDetailRegistrarException {
            get {
                return ResourceManager.GetString("InvalidFormulationDetailRegistrarException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار امضاء کننده فرمولاسیون، نامعتبر می باشد.
        /// </summary>
        public static string InvalidFormulationRegulatorException {
            get {
                return ResourceManager.GetString("InvalidFormulationRegulatorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دور ریز نباید کمتر و یا مساوی مقدار استفاده باشد .
        /// </summary>
        public static string MammockLessThanOrEqualUsedAmountException {
            get {
                return ResourceManager.GetString("MammockLessThanOrEqualUsedAmountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دور ریز نباید کمتر از صفر باشد.
        /// </summary>
        public static string MammockLessThanZeroException {
            get {
                return ResourceManager.GetString("MammockLessThanZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد محصول نباید خالی باشد.
        /// </summary>
        public static string ProductCodeCanNotBeNullException {
            get {
                return ResourceManager.GetString("ProductCodeCanNotBeNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد محصول باید معتبر باشد.
        /// </summary>
        public static string ProductCodeInvalidException {
            get {
                return ResourceManager.GetString("ProductCodeInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا امضاء شده است.
        /// </summary>
        public static string RegulatorSignAlreadyRegulatedException {
            get {
                return ResourceManager.GetString("RegulatorSignAlreadyRegulatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در زمان امضاء، جمع مقادیر دور ریز نباید کمتر از درصد رطوبت باشد.
        /// </summary>
        public static string RegulatorSignTheSumOfTheMammockShouldNotBeLessThanTheHumidityPercentException {
            get {
                return ResourceManager.GetString("RegulatorSignTheSumOfTheMammockShouldNotBeLessThanTheHumidityPercentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در زمان امضاء، جمع مقادیر استفاده شده نباید بیشتر از مقیاس باشد.
        /// </summary>
        public static string RegulatorSignTheSumOfTheUsedAmountShouldNotBeGreaterThanTheScaleException {
            get {
                return ResourceManager.GetString("RegulatorSignTheSumOfTheUsedAmountShouldNotBeGreaterThanTheScaleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در زمان امضاء، جزئیات فرمولاسیون نباید خالی باشد.
        /// </summary>
        public static string RegulatorSignWithEmptyItemsException {
            get {
                return ResourceManager.GetString("RegulatorSignWithEmptyItemsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقیاس نباید کمتر و یا مساوی صفر باشد.
        /// </summary>
        public static string ScaleLessThanOrEqualZeroException {
            get {
                return ResourceManager.GetString("ScaleLessThanOrEqualZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع نباید خالی باشد.
        /// </summary>
        public static string StartDateCanNotBeNullException {
            get {
                return ResourceManager.GetString("StartDateCanNotBeNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع صحیح نیست.
        /// </summary>
        public static string StartDateInvalidException {
            get {
                return ResourceManager.GetString("StartDateInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو تائید فرمولاسیون تائید نشده امکان پذیر نیست.
        /// </summary>
        public static string UnConfirmWithNoConfirmationSignException {
            get {
                return ResourceManager.GetString("UnConfirmWithNoConfirmationSignException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو امضای فرمولاسیون تائید شده امکان پذیر نیست.
        /// </summary>
        public static string UnRegulatorConfirmatorSignException {
            get {
                return ResourceManager.GetString("UnRegulatorConfirmatorSignException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو امضای، فرمولاسیون امضاء نشده امکان پذیر نیست.
        /// </summary>
        public static string UnRegulatorWithNoRegulationSignException {
            get {
                return ResourceManager.GetString("UnRegulatorWithNoRegulationSignException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار استفاده شده نباید کمتر و یا مساوی صفر باشد.
        /// </summary>
        public static string UsedAmountLessThanOrEqualZeroException {
            get {
                return ResourceManager.GetString("UsedAmountLessThanOrEqualZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد استفاده شده نباید کمتر از صفر باشد.
        /// </summary>
        public static string UsedPercentLessThanZeroException {
            get {
                return ResourceManager.GetString("UsedPercentLessThanZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد استفاده شده نباید بیشتر از 100 باشد.
        /// </summary>
        public static string UsedPercentMoreThan100Exception {
            get {
                return ResourceManager.GetString("UsedPercentMoreThan100Exception", resourceCulture);
            }
        }
    }
}
