// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoniz.CostAccounting.Database;

#nullable disable

namespace Shoniz.CostAccounting.Database.Migrations
{
    [DbContext(typeof(CostAccountingDbContext))]
    [Migration("20220420074452_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Shoniz.CostAccounting.FormulationContext.Domain.FormulationAggregate.Formulation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<Guid>("GoodsCode")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<decimal>("HumidityPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Decimal")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DateTime2");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DateTime2");

                    b.HasKey("Id");

                    b.ToTable("Formulations", "FormulationContext");
                });
#pragma warning restore 612, 618
        }
    }
}
